#ifndef VRTX_CONSTANTS_GLSL
#define VRTX_CONSTANTS_GLSL

#define VRTX_DEBUG_OFF 0
#define VRTX_DEBUG_FINAL_PASS_MARKER 1
#define VRTX_DEBUG_UV_GRADIENT 2
#define VRTX_DEBUG_MATERIAL_CATEGORY 3
#define VRTX_DEBUG_REFLECTIVE_MASK 4
#define VRTX_DEBUG_ROUGHNESS 5
#define VRTX_DEBUG_FRESNEL_FACTOR 6
#define VRTX_DEBUG_REFLECTION_WEIGHT 7
#define VRTX_DEBUG_REFLECTION_CONTRIBUTION 8

#define VRTX_DEBUG_VIEW 0 // [0 1 2 3 4 5 6 7 8] Debug view mode

// Level 3 baseline: controlled environment reflections on approved materials.
#define VRTX_ENVIRONMENT_REFLECTIONS_ENABLED 1

#if VRTX_ENVIRONMENT_REFLECTIONS_ENABLED == 1 || VRTX_DEBUG_VIEW >= VRTX_DEBUG_MATERIAL_CATEGORY
    #define VRTX_MATERIAL_DATA_ENABLED 1
#else
    #define VRTX_MATERIAL_DATA_ENABLED 0
#endif

#define VRTX_MATERIAL_UNKNOWN 0

#define VRTX_MATERIAL_WATER 1
#define VRTX_MATERIAL_GLASS 2
#define VRTX_MATERIAL_TINTED_GLASS 3
#define VRTX_MATERIAL_ICE 4
#define VRTX_MATERIAL_COPPER_FRESH 5
#define VRTX_MATERIAL_COPPER_OXIDIZED 6
#define VRTX_MATERIAL_AMETHYST 7
#define VRTX_MATERIAL_PACKED_BLUE_ICE 8
#define VRTX_MATERIAL_GOLD_LIKE 9

#define VRTX_MATERIAL_DIRT_MATTE 100
#define VRTX_MATERIAL_STONE_MATTE 101
#define VRTX_MATERIAL_SAND_MATTE 102
#define VRTX_MATERIAL_GRAVEL_MATTE 103
#define VRTX_MATERIAL_WOOD_MATTE 104
#define VRTX_MATERIAL_LEAVES_MATTE 105
#define VRTX_MATERIAL_ROUGH_TERRAIN_MATTE 106

#define VRTX_MATERIAL_CATEGORY_UNKNOWN 0
#define VRTX_MATERIAL_CATEGORY_MATTE 1
#define VRTX_MATERIAL_CATEGORY_PRIMARY_REFLECTIVE 2
#define VRTX_MATERIAL_CATEGORY_SECONDARY_SPECULAR 3
#define VRTX_MATERIAL_CATEGORY_POLISHED 4
#define VRTX_MATERIAL_CATEGORY_CRYSTALLINE 5

const float VRTX_EPSILON = 0.0001;

#endif
