#ifndef VRTX_CONSTANTS_GLSL
#define VRTX_CONSTANTS_GLSL

#define VRTX_DEBUG_OFF 0
#define VRTX_DEBUG_FINAL_PASS_MARKER 1
#define VRTX_DEBUG_UV_GRADIENT 2

#define VRTX_DEBUG_VIEW 0 // [0 1 2] Debug view mode

const float VRTX_EPSILON = 0.0001;

#endif